### PR TITLE
WIP: Create prebuild before publish

### PR DESCRIPTION
**Pull request by dorshay6**
`update-h3` will be used for development.

When someone will consume the package the prebuilt folder will be used if fits.

### CODE REVIEW

**Comment by dfellis** [comment]
Why is the entirety of the H3 repo being pulled into this repo?

**Comment by dorshay6** [comment]
Still trying to figure out the best way - this is the way they did it in node-s2 before.

**Comment by dfellis** [comment]
> Still trying to figure out the best way - this is the way they did it in node-s2 before.

Please revert it back to pulling the H3 C code by git tag. This repository should be obvious to anyone reading its source which code is binding related versus the core of the library (and it will also increase the repo size dramatically).

**Comment by dorshay6** [comment]
Then

**Pull request closed without merging**
